name: Update Leaderboard

on:
  repository_dispatch:
    types: [update_leaderboard]

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update leaderboard.json
        run: |
          echo "Updating leaderboard.json"
          echo "INPUT_TIME" >> leaderboard.json # Append new time
          # Sort and get the top 3 times
          jq 'sort | reverse | .[0:3]' leaderboard.json > tmp.json && mv tmp.json leaderboard.json

      - name: Commit and push changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add leaderboard.json
          git commit -m "Update leaderboard.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
